name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Static analysis (ktlint + detekt)
        run: ./gradlew ktlintCheck detekt --stacktrace

      - name: Unit & UI tests
        run: ./gradlew test

      - name: Assemble debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: lulan-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # --- For release signing later:
      # - name: Set up keystore
      #   run: |
      #     echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
      # - name: Assemble release
      #   run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=keystore.jks \
      #        -Pandroid.injected.signing.store.password=${{ secrets.SIGNING_STORE_PASSWORD }} \
      #        -Pandroid.injected.signing.key.alias=${{ secrets.SIGNING_KEY_ALIAS }} \
      #        -Pandroid.injected.signing.key.password=${{ secrets.SIGNING_KEY_PASSWORD }}
