name: Android CI (mobile-friendly, no wrapper required)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # ⬇️ Run Gradle WITHOUT gradlew (installs Gradle 8.7 for this job)
      - name: Run Gradle (ktlint + detekt + tests + assemble)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          arguments: |
            ktlintCheck detekt test assembleDebug
          # Optional: if your detekt config lives at config/detekt/detekt.yml, uncomment next line
          # build-root-directory: .
          # gradle-args: -Pdetekt.config=config/detekt/detekt.yml

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: lulan-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
